#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libdnf
Version  : 0.11.1
Release  : 13
URL      : https://github.com/rpm-software-management/libdnf/archive/0.11.1.tar.gz
Source0  : https://github.com/rpm-software-management/libdnf/archive/0.11.1.tar.gz
Summary  : Library providing simplified C and Python API to libsolv
Group    : Development/Tools
License  : GPL-2.0+ LGPL-2.1 LGPL-2.1+
Requires: libdnf-python3
Requires: libdnf-data
Requires: libdnf-lib
Requires: libdnf-doc
Requires: libdnf-python
BuildRequires : Sphinx
BuildRequires : cmake
BuildRequires : glibc-bin
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-introspection-1.0)
BuildRequires : pkgconfig(gtk-doc)
BuildRequires : pkgconfig(librepo)
BuildRequires : pkgconfig(libsolv)
BuildRequires : pkgconfig(rpm)
BuildRequires : popt-dev
BuildRequires : python3-dev
Patch1: 0001-Add-findlibsolv-cmake-file.patch
Patch2: 0002-sphinx-build-isn-t-postfixed-with-3.patch

%description
A Library providing simplified C and Python API to libsolv.

%package data
Summary: data components for the libdnf package.
Group: Data

%description data
data components for the libdnf package.


%package dev
Summary: dev components for the libdnf package.
Group: Development
Requires: libdnf-lib
Requires: libdnf-data
Provides: libdnf-devel

%description dev
dev components for the libdnf package.


%package doc
Summary: doc components for the libdnf package.
Group: Documentation

%description doc
doc components for the libdnf package.


%package lib
Summary: lib components for the libdnf package.
Group: Libraries
Requires: libdnf-data

%description lib
lib components for the libdnf package.


%package python
Summary: python components for the libdnf package.
Group: Default
Requires: libdnf-python3

%description python
python components for the libdnf package.


%package python3
Summary: python3 components for the libdnf package.
Group: Default
Requires: python3-core

%description python3
python3 components for the libdnf package.


%prep
%setup -q -n libdnf-0.11.1
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1508281928
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DCMAKE_AR=/usr/bin/gcc-ar -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_RANLIB=/usr/bin/gcc-ranlib -DPYTHON_DESIRED=3
make VERBOSE=1  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1508281928
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Dnf-1.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/libdnf/dnf-advisory.h
/usr/include/libdnf/dnf-advisorypkg.h
/usr/include/libdnf/dnf-advisoryref.h
/usr/include/libdnf/dnf-context.h
/usr/include/libdnf/dnf-db.h
/usr/include/libdnf/dnf-enums.h
/usr/include/libdnf/dnf-goal.h
/usr/include/libdnf/dnf-keyring.h
/usr/include/libdnf/dnf-lock.h
/usr/include/libdnf/dnf-package.h
/usr/include/libdnf/dnf-packagedelta.h
/usr/include/libdnf/dnf-reldep-list.h
/usr/include/libdnf/dnf-reldep.h
/usr/include/libdnf/dnf-repo-loader.h
/usr/include/libdnf/dnf-repo.h
/usr/include/libdnf/dnf-rpmts.h
/usr/include/libdnf/dnf-sack.h
/usr/include/libdnf/dnf-solution.h
/usr/include/libdnf/dnf-state.h
/usr/include/libdnf/dnf-transaction.h
/usr/include/libdnf/dnf-types.h
/usr/include/libdnf/dnf-utils.h
/usr/include/libdnf/dnf-version.h
/usr/include/libdnf/hy-goal.h
/usr/include/libdnf/hy-module-form.h
/usr/include/libdnf/hy-nevra.h
/usr/include/libdnf/hy-package.h
/usr/include/libdnf/hy-packageset.h
/usr/include/libdnf/hy-query.h
/usr/include/libdnf/hy-repo.h
/usr/include/libdnf/hy-selector.h
/usr/include/libdnf/hy-subject.h
/usr/include/libdnf/hy-types.h
/usr/include/libdnf/hy-util.h
/usr/include/libdnf/libdnf.h
/usr/lib64/libdnf.so
/usr/lib64/pkgconfig/libdnf.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
/usr/share/gtk-doc/html/libdnf/html/common.css
/usr/share/gtk-doc/html/libdnf/html/index.htm

%files lib
%defattr(-,root,root,-)
/usr/lib64/libdnf.so.1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
